const CampusActionType = {
  FETCH_ALL_CAMPUSES: "FETCH_ALL_CAMPUSES",
  DELETE_CAMPUS_BY_ID: "DELETE_CAMPUS_BY_ID",
  UPDATE_CAMPUS_DATA_BY_ID: "UPDATE_CAMPUS_DATA_BY_ID",
};

export default CampusActionType;
